### ISSUE TITLE
Error in: mglearn.plots_label_kfold() (Ch-5, In [16], page-262)

### ISSUE THREAD

**Issue by gaussEuler** [amueller/introduction_to_ml_with_python#58]
Respected Dr. Muller,
When I run the following command:
import mglearn
mglearn.plots.plot_label_kfold()

I get the following warning:
**AttributeError: module 'mglearn.plots' has no attribute 'plot_label_kfold'**

My matplotlib, mglearn versions are:
matplotlib.__version__
Out: '2.1.0'
mglearn.__version__
Out: '0.1.6'

Thank you,
Sincerely,
Nikhilesh

**Comment by amueller** [comment]
Hi. That's because there's no such function any more. Are you using the preprint version of the book?
This function is called ``plot_group_kfold`` now.

**Comment by gaussEuler** [comment]
Thank you Dr. Muller for the reply.
I am not sure whether I am using a preprint version or not: my ISBN # is:  **978-1-449-36941-5**

Thank you again,
Sincerely,
Nikhilesh

**Comment by amueller** [comment]
Hi Nikhilesh.

I just realized the first release of the book actually had ``plot_label_kfold`` in it. I changed it later because it was renamed in scikit-learn. Basically the version of the book you are using is not matched to the version of mglearn you are using. I'm sorry about the inconvenience.
This should be the only incompatible change, but I'm not 100% certain.
I mentioned this issues in the Readme now so that others can find the solution more easily: https://github.com/amueller/introduction_to_ml_with_python#errata

Please let me know if you run into further issues.

**Comment by gaussEuler** [comment]
Respected Dr. Muller,
Thank you for clarifying the issue. 

Sincerely,
Nikhilesh

**Comment by amueller** [comment]
You're welcome, and sorry again for the issue. Closing for now, let me know if anything else arises.

**Comment by SiceloKayisa** [comment]
I am here in 2024 as a beginner.

Thank you Dr Muller and Everyone for raising this.

**Comment by GaussEuler** [comment]
I learned a lot from Andreas Muller's Intro to ML book! I think, anyone who wants to pursue ML needs to look at this book first!
Thanks, Mr. Muller for your book!Sincerely,Nikhilesh    On Tuesday, March 19, 2024 at 04:36:19 AM EDT, Sicelo Kayisa ***@***.***> wrote:  
 
 


I am here in 2024 as a beginner.

Thank you Dr Muller and Everyone for raising this.
