### ISSUE TITLE
07- Text - spacy - call__() got an unexpected keyword argument 'entity'

### ISSUE THREAD

**Issue by wendlingd** [amueller/introduction_to_ml_with_python#80]
Chap 7 code works great until this line, 

```
X_train_lemma = lemma_vect.fit_transform(text_train)
```

TypeError: __call__() got an unexpected keyword argument 'entity'

Any hints on how to troubleshoot / fix?

Anaconda user; 
conda install -c spacy spacy (https://anaconda.org/spacy/spacy)

After reading other issue in your repo I ran python -m spacy download en

**Comment by amueller** [comment]
Sorry you're having issues with the code. It seems spacy changed it's interface. Can you try removing ``entity=False`` from ``doc_spacy = en_nlp(document, entity=False, parse=False)`` in ``In[38]``

**Comment by wendlingd** [comment]
Got a warning for parse=False as well. When I took both out, I got n number of the below in my console:

```
def custom_tokenizer(document):
    doc_spacy = en_nlp(document) # parse=False, entity=False, 
    return [token.lemma_ for token in doc_spacy]

/Users/myname/anaconda3/lib/python3.6/site-packages/spyder/utils/ipython/start_kernel.py:269: DeprecationWarning: [W002] Tokenizer.from_list is now deprecated. Create a new Doc object instead and pass in the strings as the `words` keyword argument, for example:
from spacy.tokens import Doc
doc = Doc(nlp.vocab, words=[...])
  main()
```
I'm using spacy 2.0.11 and looking at item 41 in your 07-working-with-text-data.ipynb; any advice? Sorry I don't know more about how to solve this.

**Comment by benbrock26** [comment]
Hi!   I got the same X_train_lemma error too!
I updated the custom_tokenizer python function.  I removed "parse = 'False' and 'entity='False'.

The core of the problem is that spacy is every evolving and the API's change too!

--> https://www.analyticsvidhya.com/blog/2017/04/natural-language-processing-made-easy-using-spacy-%E2%80%8Bin-python/

import spacy
en_nlp = spacy.load('en')
.....
.....

def custom_tokenizer(document):
    doc_spacy = en_nlp(document)
    return [token.lemma_ for token in doc_spacy]

I am experiencing the same errors as wendlingd.

#####################

Have to convert the words in the document to byte words or unicode - utf8 (word.encode("utf-8")
The trick here is to 1st tokenize the words in the document (via nltk.tokenizer or spacy.Tokenizer) 

from spacy.tokens import Doc
doc = Doc(nlp.vocab, words=[...])

Example use case 1:
doc_spacy = Doc(en_nlp.vocab, words=[u'This', u'is', u'a', u'sentence'])
doc_spacy

This is a sentence

##################################################

Example use case 2:
from spacy.tokenizer import Tokenizer
tokenizer = Tokenizer(en_nlp.vocab)

DOCUMENT = [u'Mary had a little lamb' , 
                         u'Jack went up the hill' , 
                         u'Jill followed suit' ,    
                         u'i woke up suddenly' ,
                         u'it was a really bad dream...']

tokens = [ tokenizer(DOCUMENT[idx]) for idx in range(0, len(DOCUMENT)) ]

'''
Need to come up with an easy to convert the text to unicode - 'utf-8',
'''
tokens_unicode_utf8 = ........

for doc in tokenizer.pipe(texts, batch_size=50):
     print(doc)

from spacy.tokenizer import Tokenizer
tokenizer = Tokenizer(en_nlp.vocab)

def custom_tokenizer(document):
    
    # Need to update or fix the tokens_unicode_utf8 function to convert all words to unicode - utf8.
    doc_spacy = Doc(en_nlp.vocab, words=tokens_unicode_utf8)
    return [token.lemma_ for token in doc_spacy]

def convert_text_unicode(text):
      return text.encode("utf-8')


My configuration is listed below:
Windows-10-10.0.17134-SP0
Python 3.6.1 | packaged by conda-forge | (default, May 11 2017, 19:39:41) [MSC v.1900 64 bit (AMD64)]
NumPy 1.13.1
SciPy 0.19.1
Scikit-Learn 0.19.0
pandas 0.23.0
seaborn 0.7.1
spacy 2.0.4

**Comment by benbrock26** [comment]
All, I have modified the python customize_tokenizer() function to work with the new version of spaCy-Python 3.6 for the Doc constructor.

I put print statements in the customize_tokenizer function so I knew what was going on while the code was running.

#amueller you may want to add the new code to your aml-19-text-data.ipynb.   It might a good exercise to clean the text data to remove extra symbols within the text such as '(', ')',  ",",  '.',  '?', '!', etc.   

Version of software on my Python Anaconda environment
My configuration is listed below:
Windows-10-10.0.17134-SP0
Python 3.6.1 | packaged by conda-forge | (default, May 11 2017, 19:39:41) [MSC v.1900 64 bit (AMD64)]
NumPy 1.13.1
SciPy 0.19.1
Scikit-Learn 0.19.0
pandas 0.23.0
seaborn 0.7.1
spacy 2.0.4

# Modified the custom tokenizer using the SpaCy document processing pipeline
# to work with the new Doc constructor to remove warning.
# (now using our own tokenizer)
def custom_tokenizer(document):
    from spacy.tokens import Doc
    import spacy
   
    doc_spacy = spacy.load('en')   # --> set the language to English
    doc = doc_spacy(document)      # --> set the document vocab
    
    print("custom_tokenizer::SIZE OF document: ", len(document))
    print("custom_tokenizer::type of document: {}".format(type(document)))
    print("custom_tokenizer::document:\n{}\n".format(document))
    
    # Use Doc constructor with vocabulary and words
    doc_spacy = Doc(doc.vocab, words=[t.text for t in doc])

    token_lemma_data = [token.lemma_ for token in doc_spacy]
   
    print("custom_tokenizer::Token Lemma:\n{}\n".format(result))
  
    return token_lemma_data


- Cheers

**Comment by benbrock26** [comment]
There is still one open issue with this notebook:

Issue 1) Variable text_train_sub

What is the value of text_train_sub?
There are many cells where the text_train_sub it is used.   This variable has never been set or defined in the ipython notebook.

This is the error that I got:
NameError: name 'text_train_sub' is not defined

**Comment by benbrock26** [comment]
# amueller, 
  The Undefined text_train_sub variable "Open Issue" is associated with ipython notebook, aml-19-text-data.ipynb not 07-working-with-text-data.ipynb.  Both of these notebooks are very similar.  I hope I didn't cause any confusion.

**Comment by amueller** [comment]
@benbrock26  Can you please open an issue on the right repository for that and remove the comments here?

**Comment by amueller** [comment]
Should be 
``en_nlp = spacy.load('en', disable=['parser', 'ner'])``
for newer versions of spacy.

**Comment by RM1708** [comment]
@benbrock26. Thank you.
